# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.0-browsers
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Deploy Master to Heroku
          command: |
            bash ./.circleci/add-ssh-hosts.sh
            git remote -v
            bash ./.circleci/install-packages.sh
            bash ./.circleci/deploy-heroku.sh 